### ISSUE TITLE
Spawn egg animals

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#47] opened 2021-01-27 11:42 UTC
Hello, I have a problem with mob eggs

I currently have all the permissions on the island there are no animals so the limit is 128. no animal eggs works with a / summon it works without forgetting that the eggs of aggressive mobs works

**Comment by OmerBenGera** [comment] 2021-01-27 17:15
I don't understand what the issue is

**Comment by LeRoiDamien** [comment] 2021-01-27 18:08
the problem is that we cannot put animals on certain islands so when I deactivate the SuperiorSkyblock plugin I can

**Comment by OmerBenGera** [comment] 2021-01-28 11:51
You might not have the permission to spawn animals / animals spawning is disabled on the island.
If you mean vanilla spawning, the issue might be that the island is too small, as animals don't spawn near players

**Comment by LeRoiDamien** [comment] 2021-01-28 14:58
Yes the animal spawn works very well but the problem comes from the eggs

**Comment by OmerBenGera** [comment] 2021-01-28 15:03
Only animals from eggs do not spawn? What about spawners?

**Comment by LeRoiDamien** [comment] 2021-01-28 15:07
just the animal eggs, the spawner works very well

**Comment by OmerBenGera** [comment] 2021-01-29 15:14
Are you sure it's related to SSB? Mind taking a video of the issue?

**Comment by LeRoiDamien** [comment] 2021-01-29 16:04
I just noticed that in the settings the eggs work with 'Animal spawner' I'm sorry

**Comment by OmerBenGera** [comment] 2021-01-29 16:50
Great :)
I am closing this for now

**Closed by OmerBenGera** 2021-01-29 16:50 UTC
Labels: Bug Report, Lacks information, Needs investigation
