### ISSUE TITLE
Wildstacker Support

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [OmerBenGera/SuperiorSkyblock2#79] opened 2021-02-17 23:39 UTC
I'm having an issue where the correct amount of spawners and the value isn't displaying correctly (/is top and worth placeholder)

https://pastebin.com/3m9VSajV

Worth Config https://pastebin.com/3m9VSajV
/is top values https://pastebin.com/u3xERDLz

Using:
SuperiorSkyblock2-b62.jar
WildStacker-3.5.1.jar (Later versions break mob stacking and stuff on 1.16.5)
1.16.5 Paper Fork

**Comment by YouSeeMeRunning2** [comment] 2021-02-17 23:39
![image](https://user-images.githubusercontent.com/61563491/108282372-67b79c80-7179-11eb-8b41-e68314ffe29f.png)
![image](https://user-images.githubusercontent.com/61563491/108282387-6b4b2380-7179-11eb-9f34-a167a6349ee3.png)

**Comment by OmerBenGera** [comment] 2021-02-18 14:14
It works fine for me, however I fixed an issue with an error caused by the RoseStacker so it might be that.
I pushed a fix for that, so let me know if by updating to latest dev build of SuperiorSkyblock it works or not

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 14:31
![image](https://user-images.githubusercontent.com/61563491/108371582-ce7a9b80-71f5-11eb-83aa-19d427350735.png)
I've updated to the latest dev build for superiorskyblock and it doesn't even display the correct values or amounts now
![image](https://user-images.githubusercontent.com/61563491/108371689-ebaf6a00-71f5-11eb-90aa-3d5aadceed5d.png)
'MOB_SPAWNER:IRON_GOLEM': 10000000
'MOB_SPAWNER:SHEEP': 400000
'MOB_SPAWNER:ZOMBIE': 420000
'MOB_SPAWNER:ZOMBIFIED_PIGLIN': 1750000
'MOB_SPAWNER:TURTLE': 5000000
'MOB_SPAWNER:COW': 450000
'MOB_SPAWNER:VILLAGER': 3500000
'MOB_SPAWNER:ENDERMAN': 1500000
'MOB_SPAWNER:SKELETON': 450000
'MOB_SPAWNER:BLAZE': 1250000

**Comment by OmerBenGera** [comment] 2021-02-18 14:50
You're doing something wrong as it works fine for me.
Use latest version of WildStacker as well.

**Comment by OmerBenGera** [comment] 2021-02-18 14:50
Wait, you need to use "SPAWNER:COW" etc, not "MOB_SPAWNER" - correct your spawner types.

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:01
![image](https://user-images.githubusercontent.com/61563491/108375621-0a176480-71fa-11eb-9d37-ca80322257e6.png)
Spanwer amount still counts as x1 on /is top and mobs aren't stacking and only spawn x1 mob no matter the spawner amount

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:01
![Uploading image.png…]()

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:02
![image](https://user-images.githubusercontent.com/61563491/108375834-421ea780-71fa-11eb-8072-3e5dcbd8f766.png)

**Comment by OmerBenGera** [comment] 2021-02-18 15:04
You can clearly see why the don't stack - their names are blacklisted. Look for the names blacklist section in WildStacker.
ABout them not counted towards the island top - did you change the worth file with the correct material types?

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:08
> You can clearly see why the don't stack - their names are blacklisted. Look for the names blacklist section in WildStacker.
You can see my config on the left. I don't have the mob names blacklisted

> ABout them not counted towards the island top - did you change the worth file with the correct material types?
I updated the values to -
'SPAWNER:IRON_GOLEM': 10000000
'SPAWNER:SHEEP': 400000
'SPAWNER:ZOMBIE': 420000
'SPAWNER:ZOMBIFIED_PIGLIN': 1750000
'SPAWNER:TURTLE': 5000000
'SPAWNER:COW': 450000
'SPAWNER:VILLAGER': 3500000
'SPAWNER:ENDERMAN': 1500000
'SPAWNER:SKELETON': 450000
'SPAWNER:BLAZE': 1250000

**Comment by OmerBenGera** [comment] 2021-02-18 15:31
Place the spawners again and it should work.

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:44
Restarted the server and created a new island 
![image](https://user-images.githubusercontent.com/61563491/108381863-24ecd780-7200-11eb-9801-692fa566ae91.png)

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 15:46
https://pastebin.com/5J4d8zW2 Wildstacker config
![image](https://user-images.githubusercontent.com/61563491/108382248-8614ab00-7200-11eb-9f5e-b06b732f3f21.png)

**Comment by OmerBenGera** [comment] 2021-02-18 16:07
About WS: you have blacklisted all names that have a white color in them. just set the names blacklist to empty as described in the comment of the section.
About SSB: take a video of how you place the spawners, as I can't replicate the issue

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 16:19
> About WS: you have blacklisted all names that have a white color in them. just set the names blacklist to empty as described in the comment of the section.
> About SSB: take a video of how you place the spawners, as I can't replicate the issue

I tested with wildstacker and superiorskyblock on a blank server and found that it does work. I'll start removing plugins to find the issue https://gyazo.com/3e122798dcbe34e1152296cec8739549

**Comment by OmerBenGera** [comment] 2021-02-18 16:22
Do you have other spawners plugin or something?
Try setting the spawners provider in SSB's config to WildStacker instead of Auto, maybe it fixes the issue

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 16:26
AdvancedSpawners. thought that I got rid of that plugin as it doesn't work with your one well

**Comment by YouSeeMeRunning2** [comment] 2021-02-18 16:27
Was the issue :)

**Closed** 2021-02-18 16:34 UTC
Labels: Bug Report, Needs investigation

**Comment by OmerBenGera** [comment] 2021-02-18 16:49
Hmm, might be an issue with SSB and AS with the combination of WS.
Do you want to keep investigating the issue?
