### ISSUE TITLE
Issue with EpicSpawners' custom item spawners and island blocks menu(/is blocks)/island block limits(config.yml)

### ISSUE THREAD

**Issue by ch1ll1n** [OmerBenGera/SuperiorSkyblock2#51] opened 2021-01-29 01:05 UTC
Hello,

I am using EpicSpawners 7.0.5 and the latest build of SSB2. I created some custom item spawners with EpicSpawners. When I put this spawner on the island, 3 different spawners appear in the /is blocks menu (sometimes it can be 2, IDK why exactly). When I break the spawner I placed, only 1 spawner is disappearing from the menu. Other spawners still continue to appear. Every time I put a spawner and break it, it does not disappear from the menu, so after a while, the mob spawner limit I set reaches max. In short, the plugin cannot detect that I broke the custom item spawners I broke.

**Comment by OmerBenGera** [comment] 2021-01-29 10:52
Hey, next time, use the old issue as it's pretty much the same issue - calculation errors with custom spawners.
Can you take a video of the issue please?

**Comment by ch1ll1n** [comment] 2021-01-29 12:39
https://youtu.be/3ffM1AV1SZ0

**Comment by OmerBenGera** [comment] 2021-01-29 14:53
Check out latest dev build. hopefully will fix the issue

**Comment by ch1ll1n** [comment] 2021-01-29 15:33
I am using b49 already.

**Comment by OmerBenGera** [comment] 2021-01-29 15:39
oops my bad, I forgot to upload the fix - check out build 50

**Comment by ch1ll1n** [comment] 2021-01-29 16:58
Now I tested everything works very well, but when I put the spawner, 2 different spawners appear in the blocks menu, and if I put more spawners or break the spawner, the quantities change in both. But as I said, everything works fine, it doesn't create any worth or limit bugs. Only 1 extra spawner appears in the menu.

**Comment by OmerBenGera** [comment] 2021-01-29 17:05
> 
> 
> Now I tested everything works very well, but when I put the spawner, 2 different spawners appear in the blocks menu, and if I put more spawners or break the spawner, the quantities change in both. But as I said, everything works fine, it doesn't create any worth or limit bugs. Only 1 extra spawner appears in the menu.

That's because one of the spawners is for the total spawners (all spawners from all types), and one is your custom spwaners. Therefore, it seems like an intended behavior :)

Closing this for now, if there are more issues with EpicSpawners regarding this in the next few days, just send it here

**Closed by OmerBenGera** 2021-01-29 17:05 UTC
Labels: Bug Report, Potential fix
