### ISSUE TITLE
Errors when trying to create or disband island

### ISSUE THREAD

**Issue by limaseed** [OmerBenGera/SuperiorSkyblock2#121] opened 2021-03-20 08:25 UTC
https://pastebin.com/h811KM0Q
https://pastebin.com/d4AgaEQD
Running Paper 1.16.5
SuperiorSkyblock2 v1.5.2-DEVb98

i get these errors with a fresh build, with no other plugins than SSB

**Comment by OmerBenGera** [comment] 2021-03-20 13:28
Duplicate of #109

**Closed by OmerBenGera** 2021-03-20 13:28 UTC
